/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorMenuRouteImport } from './routes/vendor.menu'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as DeliveryDashboardRouteImport } from './routes/delivery.dashboard'
import { Route as DeliveryActiveRouteImport } from './routes/delivery.active'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMenuRoute = VendorMenuRouteImport.update({
  id: '/vendor/menu',
  path: '/vendor/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryDashboardRoute = DeliveryDashboardRouteImport.update({
  id: '/delivery/dashboard',
  path: '/delivery/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryActiveRoute = DeliveryActiveRouteImport.update({
  id: '/delivery/active',
  path: '/delivery/active',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/menu': typeof VendorMenuRoute
  '/vendor/orders': typeof VendorOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/home'
    | '/login'
    | '/orders'
    | '/register'
    | '/admin/dashboard'
    | '/delivery/active'
    | '/delivery/dashboard'
    | '/restaurant/$id'
    | '/vendor/dashboard'
    | '/vendor/menu'
    | '/vendor/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/home'
    | '/login'
    | '/orders'
    | '/register'
    | '/admin/dashboard'
    | '/delivery/active'
    | '/delivery/dashboard'
    | '/restaurant/$id'
    | '/vendor/dashboard'
    | '/vendor/menu'
    | '/vendor/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/home'
    | '/login'
    | '/orders'
    | '/register'
    | '/admin/dashboard'
    | '/delivery/active'
    | '/delivery/dashboard'
    | '/restaurant/$id'
    | '/vendor/dashboard'
    | '/vendor/menu'
    | '/vendor/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DeliveryActiveRoute: typeof DeliveryActiveRoute
  DeliveryDashboardRoute: typeof DeliveryDashboardRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorMenuRoute: typeof VendorMenuRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/menu': {
      id: '/vendor/menu'
      path: '/vendor/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof VendorMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/dashboard': {
      id: '/delivery/dashboard'
      path: '/delivery/dashboard'
      fullPath: '/delivery/dashboard'
      preLoaderRoute: typeof DeliveryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/active': {
      id: '/delivery/active'
      path: '/delivery/active'
      fullPath: '/delivery/active'
      preLoaderRoute: typeof DeliveryActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DeliveryActiveRoute: DeliveryActiveRoute,
  DeliveryDashboardRoute: DeliveryDashboardRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorMenuRoute: VendorMenuRoute,
  VendorOrdersRoute: VendorOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
